default: &default
  project_id: <%= ENV["GOOGLE_PROJECT_ID"] %>
  keyfile: <%= ENV["GOOGLE_APPLICATION_CREDENTIALS"] %>

development:

production:
  <<: *default
  gcs_bucket: <%= ENV["GCS_BUCKET_NAME"] %>
